export const TYPE_BIND_UID = "BIND_UID";
export const TYPE_SEND_MSG_TO_ROOM = "SEND_MSG_TO_ROOM";
export const TYPE_RECEIVE_MSG_FROM_ROOM = "RECEIVE_MSG_FROM_ROOM";
export const TYPE_SEND_MSG_TO_USER = "SEND_MSG_TO_USER";
export const TYPE_RECEIVE_MSG_FROM_USER = "RECEIVE_MSG_FROM_USER";
export const TYPE_JOIN_ROOM = "JOIN_ROOM";
export const TYPE_JOIN_ROOM_RESPONSE = "JOIN_ROOM_RESPONSE";
export const TYPE_LEAVE_ROOM = "LEAVE_ROOM";

