exports.TYPE_CONNECTION = "connection";
exports.TYPE_DISCONNECT = "disconnect";

exports.TYPE_BIND_UID = "BIND_UID";
exports.TYPE_SEND_MSG_TO_ROOM = "SEND_MSG_TO_ROOM";
exports.TYPE_RECEIVE_MSG_FROM_ROOM = "RECEIVE_MSG_FROM_ROOM";
exports.TYPE_SEND_MSG_TO_USER = "SEND_MSG_TO_USER";
exports.TYPE_RECEIVE_MSG_FROM_USER = "RECEIVE_MSG_FROM_USER";
exports.TYPE_JOIN_ROOM = "JOIN_ROOM";
exports.TYPE_JOIN_ROOM_BROADCAST = "JOIN_ROOM_BROADCAST";
exports.TYPE_JOIN_ROOM_RESPONSE = "JOIN_ROOM_RESPONSE";
exports.TYPE_LEAVE_ROOM = "LEAVE_ROOM";
exports.TYPE_LEAVE_ROOM_BROADCAST = "LEAVE_ROOM_BROADCAST";

exports.INITIAL_ROOM = "INITIAL_ROOM";

